### ISSUE TITLE
ygopro -j regression

### ISSUE THREAD

**Issue by Zayelion** [IceYGO/ygopro#5] opened 2015-11-06 07:14 UTC
Using the following system.conf Im unable to connect to my server properly. When I open the client and go to lan mode I notice that the string is cut down to `200OOO8000,0,5,1,U,` Its missing the 5 randomly generated UID characters.

> use_d3d = 0
antialias = 0
errorlog = 1
nickname = AccessDenied
roompass = 200OOO8000,0,5,1,U,dKLTJ
lastdeck = Cyberdark Legacy - Dragons Sin
textfont = fonts/alpha.otf 13
serverport = 8911
lastip = 192.99.11.19
lastport = 8911
numfont = fonts/arialbd.ttf
fullscreen = 0
enable_sound = 1
sound_volume = 50
enable_music = 0
music_volume = 50
skin_index = 0
auto_card_placing = 1
random_card_placing = 0
auto_chain_order = 1
no_delay_for_chain = 0
enable_sleeve_loading = 0

After reopening the client it generated this 
>#config file
#nickname & gamename should be less than 20 characters
use_d3d = 0
allow_resize = 0
antialias = 0
errorlog = 1
nickname = AccessDenied
gamename = 
lastdeck = Cyberdark Legacy - Dragons Sin
textfont = fonts/alpha.otf 13
numfont = fonts/arialbd.ttf
serverport = 8911
skin_index = 0
lastip = 192.99.11.19
lastport = 8911

I believe `gamename` is ment to be `roompass` and the variant Im used to has the roompass extended to 25.

**Edit:**
30 actually according to git history:
https://github.com/SalvationDevelopment/ygopro-salvation-custom/commit/31061509d65bc34a0c6479515cbc544927a1101f#diff-5d92a305aea95aafa62adfa90d17a763
https://github.com/SalvationDevelopment/ygopro-salvation-custom/commit/9ceb453c4630dcab7d1d8be46cc9053fd9ffc5f4

**Edit:**
Im submiting a pull request with a possible fix: https://github.com/IceYGO/ygopro/pull/6

**Comment by IceYGO** [comment] 2015-11-06 09:37
This indeed was not a bug, just a missing feature. #6 merged.

**Closed by IceYGO** 2015-11-06 09:37 UTC
